Algoritmo "Atividade-A"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 
// Descrição   :
// Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Wellington Ferreira Lopes
// Data atual  : 17/09/2023
Var
// Seção de Declarações das variáveis 
  x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x<-14
repita (x)
x <-  x + 1
Escreval(X)
ate (X = 500)


Fimalgoritmo